version: "3"
services:
  tor:
    container_name: tor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9050:9050
      - 9051:9051
    restart: always
    stop_grace_period: 1m